# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Pickleball Analizador Launcher!
  displayName: 'Analizador de picleball'

- script: |
    pip install PIL
    pip install cv2
    pip install opencv-python
    pip install yolov3
    pip install imutils
    pip install pandas
    pip install -r requirements.txt
    python3 predict_video.py --input_video_path=VideoInput/video_input3.mp4 --output_video_path=VideoOutput/video_output.mp4 --minimap=0 --bounce=0
    python3 predict_video.py --input_video_path=pickleball.mp4 --output_video_path=pickleball_output.mp4 --minimap=1 --bounce=0 
  displayName: 'Instalar y Analizar pickleball.mp4'
